export const UPDATE_SITE_DATA = 'UPDATE_SITE_DATA';
export const ADD_DOCUMENT_ELEMENTS = 'ADD_DOCUMENT_ELEMENTS';
export const NAVIGATE_TO_PATH = 'NAVIGATE_TO_PATH';
export const SCROLL_TO_TOP = 'SCROLL_TO_TOP';
export const SET_AI_BUILDER_COLORS = 'SET_AI_BUILDER_COLORS';
export const UPDATE_ELEMENT_POSITIONS = 'UPDATE_ELEMENT_POSITIONS';
export const UPDATE_SCROLL_POSITION = 'UPDATE_SCROLL_POSITION';
export const UPDATE_PREVIEW_PAGE_ID = 'UPDATE_PREVIEW_PAGE_ID';